name: lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make init
      - name: Analysing the code with our lint
        run: |
          make lint